[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_lottery = "3BG3Ymop2mWUyd3twAnb42y57WvbFQ6xGuua7TVvDU6K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/snndmaa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
